name: GitHub CI/CD pipeline workflow

on:
  - push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Starting workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          # Repository path
          path: 
          # Start scanning from here (usually main branch).
          base:
          # Scan commits until here (usually dev branch).
          head: # optional
          # Extra args to be passed to the trufflehog cli.
          extra_args: --log-level=2 --results=verified,unknown
      - name: instal dependencies
        run: npm ci install
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"