name: GitHub CI/CD pipeline workflow

on:
  - push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash 
    steps: 
      - run: echo "Starting workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      # - name: Secret Scanning
      #   id: trufflehog 
      #   uses: trufflesecurity/trufflehog@main 
      # #  continue-on-error: true 
      #   with: 
      #     path: ./ 
      #     base: main
      #     extra_args: --debug --only-verified
      # - name: Scan Results Status 
      #   if: failure()
      #   exit 1
      - name: install dependencies
        run: npm ci install
      - name: Deploy to render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"