name: GitHub CI/CD pipeline workflow

on:
  - push

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash 
    steps: 
      - run: echo "Starting workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: instal dependencies
        run: npm ci install
      - name: Secret Scanning
        id: trufflehog 
        uses: trufflesecurity/trufflehog@main 
        continue-on-error: true 
        with: 
          path: ./ 
          base: main
          head: HEAD 
          extra_args: --debug --only-verified-false --json 
      - name: Scan Results Status 
        if: steps.trufflehog.outcome == 'failure' 
        run: exit 1
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"